apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: karlakuntalikhitha/php-app:latest  # You can use :latest or :${GITHUB_SHA}
        ports:
        - containerPort: 80


