name: Build and Deploy to EC2 Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/php-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/php-app:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting Minikube..."
            minikube start --driver=docker

            echo "Creating k8s folder if not exists..."
            mkdir -p ~/k8s

            echo "Copying manifests..."
            cp -r ~/php-app/k8s/* ~/k8s/

            echo "Updating image tag..."
            sed -i "s|image: .*/php-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/php-app:${{ github.sha }}|g" ~/k8s/deployment.yml

            echo "Applying Kubernetes manifests..."
            kubectl apply -f ~/k8s/deployment.yml
            kubectl apply -f ~/k8s/service.yml

          
